I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/pride.rpy", line 1253, in script
    if studygrade == 1:
  File "game/pride.rpy", line 1253, in <module>
    if studygrade == 1:
NameError: name 'studygrade' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/pride.rpy", line 1253, in script
    if studygrade == 1:
  File "C:\Users\Kimberly\Pictures\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Kimberly\Pictures\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Kimberly\Pictures\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/pride.rpy", line 1253, in <module>
    if studygrade == 1:
NameError: name 'studygrade' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
CU_HEdoubleL 1.0
Sun May 17 14:19:57 2020
